version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    image: web
    container_name: web
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment: 
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    image: web
    environment: 
      - REDIS_URL=redis://redis:6379
    command: rq worker --url redis://redis:6379 --with-scheduler
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis